In [6]:
import tensorflow as tf

In [3]:
x = tf.range(4, dtype=tf.float32)

In [4]:
x = tf.Variable(x)

In [11]:
with tf.GradientTape() as t:
  y = 2 * tf.tensordot(x, x, axes=1)

In [8]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=28.0>

In [12]:
x_grad = t.gradient(y, x)

In [13]:
x_grad

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.,  4.,  8., 12.], dtype=float32)>

In [14]:
with tf.GradientTape(persistent=True) as t:
  y = x * x
  u = tf.stop_gradient(y)
  z = u * x

x_grad = t.gradient(z, x)
x_grad == u

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True,  True,  True,  True])>

In [15]:
t.gradient(y, x) == 2 * x

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True,  True,  True,  True])>

In [16]:
def f(a):
  b = a * 2
  while tf.norm(b) < 1000:
    b = b * 2
  if tf.reduce_sum(b) > 0:
    c = b
  else:
    c = 100 * b
  return c

In [17]:
a = tf.Variable(tf.random.normal(shape=()))
with tf.GradientTape() as t:
  d = f(a)
d_grad = t.gradient(d, a)
d_grad

<tf.Tensor: shape=(), dtype=float32, numpy=8192.0>

In [19]:
d_grad == d / a

<tf.Tensor: shape=(), dtype=bool, numpy=True>